In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
canada = pd.read_csv('../Resources/CanSIPS_IC4_MEMBER_LDC.csv')
canada['LDC_SST_CanSIPS_IC4'] = canada['LDC_SST_CanSIPS_IC4'] - 273.15
canada['MON'] = pd.to_datetime(canada['MON'], format = '%H%M %d %b %Y')
canada['START'] = canada['MON'].dt.month
canada['TARGET'] = ((canada['START'] + canada['L']).astype(int))%12
canada['TARGET'] = canada['TARGET'].apply(lambda x: 12 if x == 0 else x)

# Calculate the mean grouped by 'L' and 'START'
canada_mean = canada.groupby(['L', 'START', 'M'])['LDC_SST_CanSIPS_IC4'].mean().reset_index()
canada_mean.rename(columns={'LDC_SST_CanSIPS_IC4': 'MEAN_SST_CanSIPS_IC4'}, inplace=True)

# Calculate the variance grouped by 'L' and 'START'
canada_var = canada.groupby(['L', 'START', 'M'])['LDC_SST_CanSIPS_IC4'].var().reset_index()
canada_var.rename(columns={'LDC_SST_CanSIPS_IC4': 'VAR_SST_CanSIPS_IC4'}, inplace=True)

# Merge the mean and variance DataFrames
canada_stat = pd.merge(canada_mean, canada_var, on=['M','L','START'])
month_to_season = {
    1: 'DJF', 2: 'JFM', 3: 'FMA', 4: 'MAM', 5: 'AMJ', 6: 'MJJ',
    7: 'JJA', 8: 'JAS', 9: 'ASO', 10: 'SON', 11: 'OND', 12: 'NDJ'
}
canada_stat['TARGET'] = ((canada_stat['START'] + canada_stat['L']).astype(int))%12
canada_stat['TARGET'] = canada_stat['TARGET'].apply(lambda x: 12 if x == 0 else x)
canada_stat['SZN'] = canada_stat['TARGET'].map(month_to_season)

new_order = ['M','L','START','TARGET','SZN','MEAN_SST_CanSIPS_IC4','VAR_SST_CanSIPS_IC4']
canada_stat = canada_stat[new_order]

canada_stat.to_csv('../Resources/canada_member_stat.csv', index=False)
canada_stat

       M     L  START  TARGET  SZN  MEAN_SST_CanSIPS_IC4  VAR_SST_CanSIPS_IC4
0      1   1.5      1       2  JFM             26.044670             1.406593
1      2   1.5      1       2  JFM             26.051510             1.326273
2      3   1.5      1       2  JFM             26.096257             1.284487
3      4   1.5      1       2  JFM             25.995270             1.414336
4      5   1.5      1       2  JFM             26.020743             1.354581
...   ..   ...    ...     ...  ...                   ...                  ...
4795  36  10.5     12      10  SON             27.040617             0.439935
4796  37  10.5     12      10  SON             26.930810             0.292096
4797  38  10.5     12      10  SON             27.005680             0.419922
4798  39  10.5     12      10  SON             27.074583             0.359692
4799  40  10.5     12      10  SON             26.973760             0.318442

[4800 rows x 7 columns]

In [2]:
 """SOURCES .Models .NMME .CanSIPS-IC4 .HINDCAST .MONTHLY .sst
  S (0000 1 Jan-Dec 1991-2020) RANGE
  Y -5 5 RANGEEDGES
  X 190 240 RANGEEDGES
  M 0.5 40.5 RANGEEDGES
  [X Y]average
  L 3 runningAverage"""

'SOURCES .Models .NMME .CanSIPS-IC4 .HINDCAST .MONTHLY .sst\n S (0000 1 Jan-Dec 1991-2020) RANGE\n Y -5 5 RANGEEDGES\n X 190 240 RANGEEDGES\n M 0.5 40.5 RANGEEDGES\n [X Y]average\n L 3 runningAverage'

In [4]:
canesm = pd.read_csv('../Resources/CanESM5_MEMBER_LDC.csv')
canesm['LDC_SST_CanESM5'] = canesm['LDC_SST_CanESM5'] - 273.15
canesm['MON'] = pd.to_datetime(canesm['MON'], format = '%H%M %d %b %Y')
canesm['START'] = canesm['MON'].dt.month
canesm['TARGET'] = ((canesm['START'] + canesm['L']).astype(int))%12
canesm['TARGET'] = canesm['TARGET'].apply(lambda x: 12 if x == 0 else x)

# Calculate the mean grouped by 'L' and 'START'
canesm_mean = canesm.groupby(['L', 'START', 'M'])['LDC_SST_CanESM5'].mean().reset_index()
canesm_mean.rename(columns={'LDC_SST_CanESM5': 'MEAN_SST_CanESM5'}, inplace=True)

# Calculate the variance grouped by 'L' and 'START'
canesm_var = canesm.groupby(['L', 'START', 'M'])['LDC_SST_CanESM5'].var().reset_index()
canesm_var.rename(columns={'LDC_SST_CanESM5': 'VAR_SST_CanESM5'}, inplace=True)

# Merge the mean and variance DataFrames
canesm_stat = pd.merge(canesm_mean, canesm_var, on=['M','L','START'])
month_to_season = {
    1: 'DJF', 2: 'JFM', 3: 'FMA', 4: 'MAM', 5: 'AMJ', 6: 'MJJ',
    7: 'JJA', 8: 'JAS', 9: 'ASO', 10: 'SON', 11: 'OND', 12: 'NDJ'
}
canesm_stat['TARGET'] = ((canesm_stat['START'] + canesm_stat['L']).astype(int))%12
canesm_stat['TARGET'] = canesm_stat['TARGET'].apply(lambda x: 12 if x == 0 else x)
canesm_stat['SZN'] = canesm_stat['TARGET'].map(month_to_season)

new_order = ['M','L','START','TARGET','SZN','MEAN_SST_CanESM5','VAR_SST_CanESM5']
canesm_stat = canesm_stat[new_order]

canesm_stat.to_csv('../Resources/canesm_member_stat.csv', index=False)
canesm_stat

         M   L  START  TARGET  SZN  MEAN_SST_CanESM5  VAR_SST_CanESM5
0      1.5   1      1       2  JFM         27.060410         0.901011
1      2.5   1      1       2  JFM         27.419760         0.612122
2      3.5   1      1       2  JFM         27.762300         0.443864
3      4.5   1      1       2  JFM         27.887827         0.365120
4      5.5   1      1       2  JFM         27.745033         0.320493
...    ...  ..    ...     ...  ...               ...              ...
2395   6.5  20     12       8  JAS         27.634540         0.537240
2396   7.5  20     12       8  JAS         27.348570         0.373144
2397   8.5  20     12       8  JAS         27.103127         0.270120
2398   9.5  20     12       8  JAS         26.989200         0.251886
2399  10.5  20     12       8  JAS         26.973760         0.318442

[2400 rows x 7 columns]

In [ ]:
 '''SOURCES .Models .NMME .CanSIPS-IC4 .CanESM5 .HINDCAST .MONTHLY .sst
  S (0000 1 Jan-Dec 1991-2020) RANGE
  Y -5 5 RANGEEDGES
  X 190 240 RANGEEDGES
  M 0.5 40.5 RANGEEDGES
  [X Y]average
  L 3 runningAverage
'''

In [5]:
nemo = pd.read_csv('../Resources/GEM52_NEMO_MEMBER_LDC.csv')
nemo['LDC_SST_GEM52_NEMO'] = nemo['LDC_SST_GEM52_NEMO'] - 273.15
nemo['MON'] = pd.to_datetime(nemo['MON'], format = '%H%M %d %b %Y')
nemo['START'] = nemo['MON'].dt.month
nemo['TARGET'] = ((nemo['START'] + nemo['L']).astype(int))%12
nemo['TARGET'] = nemo['TARGET'].apply(lambda x: 12 if x == 0 else x)

# Calculate the mean grouped by 'L' and 'START'
nemo_mean = nemo.groupby(['L', 'START', 'M'])['LDC_SST_GEM52_NEMO'].mean().reset_index()
nemo_mean.rename(columns={'LDC_SST_GEM52_NEMO': 'MEAN_SST_GEM52_NEMO'}, inplace=True)

# Calculate the variance grouped by 'L' and 'START'
nemo_var = nemo.groupby(['L', 'START', 'M'])['LDC_SST_GEM52_NEMO'].var().reset_index()
nemo_var.rename(columns={'LDC_SST_GEM52_NEMO': 'VAR_SST_GEM52_NEMO'}, inplace=True)

# Merge the mean and variance DataFrames
nemo_stat = pd.merge(nemo_mean, nemo_var, on=['M','L','START'])
month_to_season = {
    1: 'DJF', 2: 'JFM', 3: 'FMA', 4: 'MAM', 5: 'AMJ', 6: 'MJJ',
    7: 'JJA', 8: 'JAS', 9: 'ASO', 10: 'SON', 11: 'OND', 12: 'NDJ'
}
nemo_stat['TARGET'] = ((nemo_stat['START'] + nemo_stat['L']).astype(int))%12
nemo_stat['TARGET'] = nemo_stat['TARGET'].apply(lambda x: 12 if x == 0 else x)
nemo_stat['SZN'] = nemo_stat['TARGET'].map(month_to_season)

new_order = ['M','L','START','TARGET','SZN','MEAN_SST_GEM52_NEMO','VAR_SST_GEM52_NEMO']
nemo_stat = nemo_stat[new_order]

nemo_stat.to_csv('../Resources/nemo_member_stat.csv', index=False)
nemo_stat

       M     L  START  TARGET  SZN  MEAN_SST_GEM52_NEMO  VAR_SST_GEM52_NEMO
0      1   1.5      1       2  JFM            26.044670            1.406593
1      2   1.5      1       2  JFM            26.051510            1.326273
2      3   1.5      1       2  JFM            26.096257            1.284487
3      4   1.5      1       2  JFM            25.995270            1.414336
4      5   1.5      1       2  JFM            26.020743            1.354581
...   ..   ...    ...     ...  ...                  ...                 ...
2395  16  10.5     12      10  SON            23.663533            0.519245
2396  17  10.5     12      10  SON            23.634050            0.381608
2397  18  10.5     12      10  SON            23.502280            0.378929
2398  19  10.5     12      10  SON            23.760790            0.426760
2399  20  10.5     12      10  SON            23.768263            0.352933

[2400 rows x 7 columns]

In [ ]:
''' SOURCES .Models .NMME .CanSIPS-IC4 .GEM5.2-NEMO .HINDCAST .MONTHLY .sst
  S (0000 1 Jan-Dec 1991-2020) RANGE
  Y -5 5 RANGEEDGES
  X 190 240 RANGEEDGES
  M 0.5 20.5 RANGEEDGES
  [X Y]average
  L 3 runningAverage
'''