In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from functools import reduce
gfdl_old_stat = pd.read_csv('../Resources/gfdl_stat.csv')
gfdl_member_stat = pd.read_csv('../Resources/gfdl_member_stat.csv')

nasa_old_stat = pd.read_csv('../Resources/nasa_stat.csv')
nasa_member_stat = pd.read_csv('../Resources/nasa_member_stat.csv')

canada_old_stat = pd.read_csv('../Resources/canada_stat.csv')
canada_member_stat = pd.read_csv('../Resources/canada_member_stat.csv')

canesm_old_stat = pd.read_csv('../Resources/canesm_stat.csv')
canesm_member_stat = pd.read_csv('../Resources/canesm_member_stat.csv')

nemo_old_stat = pd.read_csv('../Resources/nemo_stat.csv')
nemo_member_stat = pd.read_csv('../Resources/nemo_member_stat.csv')

cola_old_stat = pd.read_csv('../Resources/cola_stat.csv')
cola_member_stat = pd.read_csv('../Resources/cola_member_stat.csv')

ncep_old_stat = pd.read_csv('../Resources/ncep_stat.csv')
ncep_member_stat = pd.read_csv('../Resources/ncep_member_stat.csv')

In [18]:
gfdl_member_stat

       M     L  START  TARGET  SZN  MEAN_SST_GFDL_SPEAR  VAR_SST_GFDL_SPEAR
0      1   1.5      1       2  JFM            26.738680            0.697007
1      2   1.5      1       2  JFM            26.732249            0.576535
2      3   1.5      1       2  JFM            26.746541            0.603709
3      4   1.5      1       2  JFM            26.735400            0.640981
4      5   1.5      1       2  JFM            26.756399            0.565600
...   ..   ...    ...     ...  ...                  ...                 ...
1795  11  10.5     12      10  SON            25.887765            0.453927
1796  12  10.5     12      10  SON            25.847967            0.662877
1797  13  10.5     12      10  SON            25.936973            0.947368
1798  14  10.5     12      10  SON            25.883585            0.598587
1799  15  10.5     12      10  SON            25.922312            0.435421

[1800 rows x 7 columns]

In [19]:
gfdl_old_stat

,L,START,TARGET,SZN,MEAN_SST_GFDL_SPEAR,VAR_SST_GFDL_SPEAR,MEAN_SST_GFDL_SPEAR_ONETWO,VAR_SST_GFDL_SPEAR_ONETWO,MEAN_SST_GFDL_SPEAR_THREE,VAR_SST_GFDL_SPEAR_THREE,MEAN_SST_GFDL_SPEAR_FOUR,VAR_SST_GFDL_SPEAR_FOUR
0,1.5,1,2,JFM,26.730966,0.586198,25.979638,0.357964,26.370009,0.625309,28.087537,0.386829
1,1.5,2,3,FMA,27.219343,0.350295,26.326895,0.359253,27.048718,0.415907,28.269656,0.241667
2,1.5,3,4,MAM,27.700019,0.219369,25.643214,0.473376,27.380241,0.258118,28.604104,0.188554
3,1.5,4,5,AMJ,27.778266,0.121108,24.430450,0.842295,27.104430,0.201826,28.747332,0.133107
4,1.5,5,6,MJJ,27.458359,0.171726,23.237966,1.147971,26.420442,0.322418,28.671299,0.155934
...,...,...,...,...,...,...,...,...,...,...,...,...
115,10.5,8,6,MJJ,27.063226,0.234518,22.834014,0.507439,25.913820,0.299097,28.364218,0.235133
116,10.5,9,7,JJA,26.551078,0.209246,21.726895,0.307037,25.141851,0.215859,28.198871,0.216735
117,10.5,10,8,JAS,26.115971,0.235266,21.025533,0.384822,24.628546,0.247013,27.969411,0.227540
118,10.5,11,9,ASO,25.949336,0.246216,20.781225,0.321545,24.463252,0.247043,27.880232,0.239703
119,10.5,12,10,SON,25.933564,0.308880,21.074116,0.332481,24.517411,0.283026,27.804294,0.310467

In [22]:

# Calculate the mean grouped by 'L' and 'START' - Nino3.4
gfdl_mean = gfdl_member_stat.groupby(['L', 'START'])['MEAN_SST_GFDL_SPEAR'].mean().reset_index()

# Calculate the variance grouped by 'L' and 'START' - Nino3.4
gfdl_var = gfdl_member_stat.groupby(['L', 'START'])['VAR_SST_GFDL_SPEAR'].mean().reset_index()


# Merge the mean and variance DataFrames
dfs = [gfdl_mean, gfdl_var]
gfdl_new_stat = reduce(lambda left, right: pd.merge(left, right, on=['L', 'START']), dfs)
gfdl_new_stat

        L  START  MEAN_SST_GFDL_SPEAR  VAR_SST_GFDL_SPEAR
0     1.5      1            26.730966            0.600480
1     1.5      2            27.219343            0.361776
2     1.5      3            27.700019            0.229501
3     1.5      4            27.778265            0.129531
4     1.5      5            27.458358            0.185918
..    ...    ...                  ...                 ...
115  10.5      8            27.063943            0.380271
116  10.5      9            26.551078            0.395347
117  10.5     10            26.115971            0.476122
118  10.5     11            25.949336            0.515503
119  10.5     12            25.933564            0.594260

[120 rows x 4 columns]

In [24]:
gfdl_old_stat['VAR_SST_GFDL_SPEAR'] = gfdl_new_stat['VAR_SST_GFDL_SPEAR']
gfdl_old_stat

,L,START,TARGET,SZN,MEAN_SST_GFDL_SPEAR,VAR_SST_GFDL_SPEAR,MEAN_SST_GFDL_SPEAR_ONETWO,VAR_SST_GFDL_SPEAR_ONETWO,MEAN_SST_GFDL_SPEAR_THREE,VAR_SST_GFDL_SPEAR_THREE,MEAN_SST_GFDL_SPEAR_FOUR,VAR_SST_GFDL_SPEAR_FOUR
0,1.5,1,2,JFM,26.730966,0.600480,25.979638,0.357964,26.370009,0.625309,28.087537,0.386829
1,1.5,2,3,FMA,27.219343,0.361776,26.326895,0.359253,27.048718,0.415907,28.269656,0.241667
2,1.5,3,4,MAM,27.700019,0.229501,25.643214,0.473376,27.380241,0.258118,28.604104,0.188554
3,1.5,4,5,AMJ,27.778266,0.129531,24.430450,0.842295,27.104430,0.201826,28.747332,0.133107
4,1.5,5,6,MJJ,27.458359,0.185918,23.237966,1.147971,26.420442,0.322418,28.671299,0.155934
...,...,...,...,...,...,...,...,...,...,...,...,...
115,10.5,8,6,MJJ,27.063226,0.380271,22.834014,0.507439,25.913820,0.299097,28.364218,0.235133
116,10.5,9,7,JJA,26.551078,0.395347,21.726895,0.307037,25.141851,0.215859,28.198871,0.216735
117,10.5,10,8,JAS,26.115971,0.476122,21.025533,0.384822,24.628546,0.247013,27.969411,0.227540
118,10.5,11,9,ASO,25.949336,0.515503,20.781225,0.321545,24.463252,0.247043,27.880232,0.239703
119,10.5,12,10,SON,25.933564,0.594260,21.074116,0.332481,24.517411,0.283026,27.804294,0.310467

In [25]:
gfdl_old_stat.to_csv('../Resources/gfdl_stat.csv', index=False)

In [30]:
# Calculate the mean grouped by 'L' and 'START' - Nino3.4
cola_mean = cola_member_stat.groupby(['L', 'START'])['MEAN_SST_COLA_CESM1'].mean().reset_index()

# Calculate the variance grouped by 'L' and 'START' - Nino3.4
cola_var = cola_member_stat.groupby(['L', 'START'])['VAR_SST_COLA_CESM1'].mean().reset_index()

# Merge the mean and variance DataFrames
dfs = [cola_mean, cola_var]
cola_new_stat = reduce(lambda left, right: pd.merge(left, right, on=['L', 'START']), dfs)

cola_old_stat['VAR_SST_COLA_CESM1'] = cola_new_stat['VAR_SST_COLA_CESM1']
cola_old_stat.to_csv('../Resources/cola_stat.csv', index=False)
cola_old_stat

,L,START,TARGET,SZN,MEAN_SST_COLA_CESM1,VAR_SST_COLA_CESM1,MEAN_SST_COLA_CESM1_ONETWO,VAR_SST_COLA_CESM1_ONETWO,MEAN_SST_COLA_CESM1_THREE,VAR_SST_COLA_CESM1_THREE,MEAN_SST_COLA_CESM1_FOUR,VAR_SST_COLA_CESM1_FOUR
0,1.5,1,2,JFM,26.716516,0.977900,23.795889,0.402321,25.912148,0.836250,28.235130,0.616628
1,1.5,2,3,FMA,27.143832,0.665144,24.444666,0.321284,26.578873,0.606206,28.353961,0.416323
2,1.5,3,4,MAM,27.680017,0.476414,24.364965,0.496226,27.031897,0.462719,28.680026,0.337920
3,1.5,4,5,AMJ,27.869485,0.283165,23.344466,0.717739,26.845577,0.370761,28.910354,0.206512
4,1.5,5,6,MJJ,27.326014,0.506587,21.945054,0.933938,25.800083,0.700835,28.821855,0.189200
...,...,...,...,...,...,...,...,...,...,...,...,...
115,10.5,8,6,MJJ,27.968482,0.953372,23.714368,0.711524,27.040492,0.747153,28.840817,0.434509
116,10.5,9,7,JJA,27.762687,1.068514,22.773825,0.895394,26.473860,0.950921,28.933831,0.318694
117,10.5,10,8,JAS,26.928002,1.637832,21.614455,1.129617,25.465826,1.292681,28.499873,0.525801
118,10.5,11,9,ASO,26.115936,1.661522,20.928485,0.767826,24.638735,1.123519,27.985525,0.661568
119,10.5,12,10,SON,25.414888,1.776513,20.647734,0.435425,23.918052,1.093075,27.464330,0.845963

In [31]:
# Calculate the mean grouped by 'L' and 'START' - Nino3.4
nasa_mean = nasa_member_stat.groupby(['L', 'START'])['MEAN_SST_NASA_GEOSS2S'].mean().reset_index()

# Calculate the variance grouped by 'L' and 'START' - Nino3.4
nasa_var = nasa_member_stat.groupby(['L', 'START'])['VAR_SST_NASA_GEOSS2S'].mean().reset_index()

# Merge the mean and variance DataFrames
dfs = [nasa_mean, nasa_var]
nasa_new_stat = reduce(lambda left, right: pd.merge(left, right, on=['L', 'START']), dfs)

nasa_old_stat['VAR_SST_NASA_GEOSS2S'] = nasa_new_stat['VAR_SST_NASA_GEOSS2S']
nasa_old_stat.to_csv('../Resources/nasa_stat.csv', index=False)
nasa_old_stat

,L,START,TARGET,SZN,MEAN_SST_NASA_GEOSS2S,VAR_SST_NASA_GEOSS2S,MEAN_SST_NASA_GEOSS2S_ONETWO,VAR_SST_NASA_GEOSS2S_ONETWO,MEAN_SST_NASA_GEOSS2S_THREE,VAR_SST_NASA_GEOSS2S_THREE,MEAN_SST_NASA_GEOSS2S_FOUR,VAR_SST_NASA_GEOSS2S_FOUR
0,1.5,1,2,JFM,26.541165,1.670046,25.531130,0.793366,25.927537,1.496384,28.209766,0.928141
1,1.5,2,3,FMA,27.122570,1.037995,26.544073,0.409274,26.801676,0.956819,28.383803,0.707556
2,1.5,3,4,MAM,27.798589,0.719993,26.189305,0.788895,27.452527,0.683433,28.805776,0.590967
3,1.5,4,5,AMJ,28.156845,0.512972,24.736159,1.815048,27.520732,0.646134,29.096188,0.394293
4,1.5,5,6,MJJ,27.886593,0.488650,22.797204,2.152622,26.735561,0.758972,29.079355,0.312939
...,...,...,...,...,...,...,...,...,...,...,...,...
79,7.5,8,3,FMA,26.401063,2.660764,24.071658,1.492322,25.748558,2.254158,28.163592,1.516919
80,7.5,9,4,MAM,26.590335,1.647455,23.271708,0.530427,25.836187,1.075207,28.121003,1.244211
81,7.5,10,5,AMJ,26.680818,1.497271,21.942472,0.573966,25.565017,1.115225,28.232630,0.979266
82,7.5,11,6,MJJ,26.873905,1.050840,21.213926,0.534098,25.493285,0.720675,28.441562,0.752294
83,7.5,12,7,JJA,26.871119,0.961526,20.661577,0.565436,25.219735,0.714508,28.572824,0.652722

In [32]:
# Calculate the mean grouped by 'L' and 'START' - Nino3.4
ncep_mean = ncep_member_stat.groupby(['L', 'START'])['MEAN_SST_NCEP_CFSv2'].mean().reset_index()

# Calculate the variance grouped by 'L' and 'START' - Nino3.4
ncep_var = ncep_member_stat.groupby(['L', 'START'])['VAR_SST_NCEP_CFSv2'].mean().reset_index()

# Merge the mean and variance DataFrames
dfs = [ncep_mean, ncep_var]
ncep_new_stat = reduce(lambda left, right: pd.merge(left, right, on=['L', 'START']), dfs)

ncep_old_stat['VAR_SST_NCEP_CFSv2'] = ncep_new_stat['VAR_SST_NCEP_CFSv2']
ncep_old_stat.to_csv('../Resources/ncep_stat.csv', index=False)
ncep_old_stat

,L,START,TARGET,SZN,MEAN_SST_NCEP_CFSv2,VAR_SST_NCEP_CFSv2,MEAN_SST_NCEP_CFSv2_ONETWO,VAR_SST_NCEP_CFSv2_ONETWO,MEAN_SST_NCEP_CFSv2_THREE,VAR_SST_NCEP_CFSv2_THREE,MEAN_SST_NCEP_CFSv2_FOUR,VAR_SST_NCEP_CFSv2_FOUR
0,1.5,1,2,JFM,26.866738,0.805979,26.395819,0.409840,26.337465,0.837696,28.272041,0.390010
1,1.5,2,3,FMA,27.219349,0.542134,26.773921,0.274441,26.889961,0.552057,28.397574,0.289991
2,1.5,3,4,MAM,27.972402,0.416445,26.529146,0.458082,27.502823,0.408028,28.971794,0.250380
3,1.5,4,5,AMJ,28.262841,0.330704,25.516843,0.878739,27.458724,0.365817,29.336631,0.161831
4,1.5,5,6,MJJ,27.570029,0.372411,24.132756,0.932746,26.461735,0.461137,28.975814,0.175833
...,...,...,...,...,...,...,...,...,...,...,...,...
91,8.5,8,4,MAM,27.909715,0.565449,28.100376,0.417416,27.952315,0.542930,28.625821,0.188721
92,8.5,9,5,AMJ,28.293730,0.441521,27.219096,0.537658,28.046387,0.451339,28.934280,0.168496
93,8.5,10,6,MJJ,28.067436,0.463146,25.593861,0.449776,27.306398,0.305740,28.981894,0.126838
94,8.5,11,7,JJA,27.334136,0.645779,24.214662,0.278926,26.237796,0.283134,28.718463,0.156606
95,8.5,12,8,JAS,26.482465,0.750419,23.511479,0.171011,25.357012,0.291227,28.247239,0.193567

In [33]:
# Calculate the mean grouped by 'L' and 'START' - Nino3.4
canada_mean = canada_member_stat.groupby(['L', 'START'])['MEAN_SST_CanSIPS_IC4'].mean().reset_index()

# Calculate the variance grouped by 'L' and 'START' - Nino3.4
canada_var = canada_member_stat.groupby(['L', 'START'])['VAR_SST_CanSIPS_IC4'].mean().reset_index()

# Merge the mean and variance DataFrames
dfs = [canada_mean, canada_var]
canada_new_stat = reduce(lambda left, right: pd.merge(left, right, on=['L', 'START']), dfs)

canada_old_stat['VAR_SST_CanSIPS_IC4'] = canada_new_stat['VAR_SST_CanSIPS_IC4']
canada_old_stat.to_csv('../Resources/canada_stat.csv', index=False)
canada_old_stat

,L,START,TARGET,SZN,MEAN_SST_CanSIPS_IC4,VAR_SST_CanSIPS_IC4,MEAN_SST_CanSIPS_IC4_ONETWO,VAR_SST_CanSIPS_IC4_ONETWO,MEAN_SST_CanSIPS_IC4_THREE,VAR_SST_CanSIPS_IC4_THREE,MEAN_SST_CanSIPS_IC4_FOUR,VAR_SST_CanSIPS_IC4_FOUR
0,1.5,1,2,JFM,26.514067,1.110209,26.054047,0.331210,26.127763,0.826451,28.027927,0.630136
1,1.5,2,3,FMA,26.901287,0.781024,26.633620,0.293816,26.715827,0.564593,28.160143,0.487491
2,1.5,3,4,MAM,27.267670,0.506803,26.332573,0.394004,26.984453,0.375192,28.408000,0.355371
3,1.5,4,5,AMJ,27.401857,0.343562,25.393937,0.459029,26.816480,0.303830,28.577727,0.250160
4,1.5,5,6,MJJ,27.154027,0.411945,24.296623,0.604740,26.209243,0.431015,28.583253,0.231162
...,...,...,...,...,...,...,...,...,...,...,...,...
115,10.5,8,6,MJJ,26.527820,0.432298,24.039950,0.159804,25.538907,0.222812,27.857983,0.211482
116,10.5,9,7,JJA,26.019560,0.393255,23.055137,0.131486,24.759867,0.160930,27.660077,0.162311
117,10.5,10,8,JAS,25.615137,0.379251,22.539690,0.127402,24.358107,0.153665,27.455523,0.159607
118,10.5,11,9,ASO,25.373080,0.371522,22.435180,0.113738,24.230670,0.124512,27.302437,0.168175
119,10.5,12,10,SON,25.344350,0.403997,22.775460,0.120343,24.347217,0.139306,27.255273,0.170298

In [34]:
# Calculate the mean grouped by 'L' and 'START' - Nino3.4
canesm_mean = canesm_member_stat.groupby(['L', 'START'])['MEAN_SST_CanESM5'].mean().reset_index()

# Calculate the variance grouped by 'L' and 'START' - Nino3.4
canesm_var = canesm_member_stat.groupby(['L', 'START'])['VAR_SST_CanESM5'].mean().reset_index()

# Merge the mean and variance DataFrames
dfs = [canesm_mean, canesm_var]
canesm_new_stat = reduce(lambda left, right: pd.merge(left, right, on=['L', 'START']), dfs)

canesm_old_stat['VAR_SST_CanESM5'] = canesm_new_stat['VAR_SST_CanESM5']
canesm_old_stat.to_csv('../Resources/canesm_stat.csv', index=False)
canesm_old_stat

,L,START,TARGET,SZN,MEAN_SST_CanESM5,VAR_SST_CanESM5,MEAN_SST_CanESM5_ONETWO,VAR_SST_CanESM5_ONETWO,MEAN_SST_CanESM5_THREE,VAR_SST_CanESM5_THREE,MEAN_SST_CanESM5_FOUR,VAR_SST_CanESM5_FOUR
0,1.5,1,2,JFM,27.029653,0.871235,26.462150,0.260184,26.575790,0.700761,28.452833,0.474052
1,1.5,2,3,FMA,27.424380,0.537901,27.275530,0.177754,27.233553,0.417070,28.566353,0.341719
2,1.5,3,4,MAM,27.817160,0.315123,27.207640,0.179394,27.580443,0.211847,28.822040,0.258164
3,1.5,4,5,AMJ,27.936003,0.239228,26.299680,0.276678,27.402647,0.191922,28.956580,0.178810
4,1.5,5,6,MJJ,27.722560,0.212050,25.042160,0.417641,26.768283,0.246930,28.976930,0.159567
...,...,...,...,...,...,...,...,...,...,...,...,...
115,10.5,8,6,MJJ,28.058473,0.336303,25.303740,0.154181,26.968580,0.178330,29.279490,0.123230
116,10.5,9,7,JJA,27.662633,0.272850,24.355967,0.161183,26.298540,0.159866,29.214907,0.110508
117,10.5,10,8,JAS,27.316313,0.220372,23.768470,0.179019,25.866157,0.138337,29.144513,0.095845
118,10.5,11,9,ASO,27.070453,0.251594,23.556747,0.171087,25.623663,0.132352,29.091003,0.108399
119,10.5,12,10,SON,26.969737,0.322821,23.774893,0.204319,25.613273,0.173856,29.050190,0.130214

In [35]:
# Calculate the mean grouped by 'L' and 'START' - Nino3.4
nemo_mean = nemo_member_stat.groupby(['L', 'START'])['MEAN_SST_GEM52_NEMO'].mean().reset_index()

# Calculate the variance grouped by 'L' and 'START' - Nino3.4
nemo_var = nemo_member_stat.groupby(['L', 'START'])['VAR_SST_GEM52_NEMO'].mean().reset_index()

# Merge the mean and variance DataFrames
dfs = [nemo_mean, nemo_var]
nemo_new_stat = reduce(lambda left, right: pd.merge(left, right, on=['L', 'START']), dfs)

nemo_old_stat['VAR_SST_GEM52_NEMO'] = nemo_new_stat['VAR_SST_GEM52_NEMO']
nemo_old_stat.to_csv('../Resources/nemo_stat.csv', index=False)
nemo_old_stat

,L,START,TARGET,SZN,MEAN_SST_GEM52_NEMO,VAR_SST_GEM52_NEMO,MEAN_SST_GEM52_NEMO_ONETWO,VAR_SST_GEM52_NEMO_ONETWO,MEAN_SST_GEM52_NEMO_THREE,VAR_SST_GEM52_NEMO_THREE,MEAN_SST_GEM52_NEMO_FOUR,VAR_SST_GEM52_NEMO_FOUR
0,1.5,1,2,JFM,25.998487,1.349184,25.645917,0.437508,26.575790,0.700761,27.602993,0.817083
1,1.5,2,3,FMA,26.378197,1.024146,25.991703,0.471538,27.233553,0.417070,27.753910,0.675770
2,1.5,3,4,MAM,26.718220,0.698483,25.457513,0.769131,27.580443,0.211847,27.993927,0.501665
3,1.5,4,5,AMJ,26.867733,0.447896,24.488183,0.786044,27.402647,0.191922,28.198853,0.345254
4,1.5,5,6,MJJ,26.585507,0.611840,23.551083,0.884779,26.768283,0.246930,28.189570,0.335501
...,...,...,...,...,...,...,...,...,...,...,...,...
115,10.5,8,6,MJJ,24.997160,0.528294,22.776180,0.210986,26.968580,0.178330,26.436457,0.367586
116,10.5,9,7,JJA,24.376450,0.513659,21.754327,0.151201,26.298540,0.159866,26.105260,0.248561
117,10.5,10,8,JAS,23.913930,0.538131,21.310933,0.138104,25.866157,0.138337,25.766543,0.264001
118,10.5,11,9,ASO,23.675670,0.491450,21.313630,0.125069,25.623663,0.132352,25.513887,0.284187
119,10.5,12,10,SON,23.718940,0.485173,21.776050,0.121571,25.613273,0.173856,25.460373,0.270538